// function that changes the background color to a random one
function handleRandom() {
  // create a random value
  let randomColor = Math.floor(Math.random() * 16777215).toString(16);

  // add # + the random value to have a hex value
  let hexbValue = "#" + randomColor;

  // insert the generated hex value to the body
  document.body.style.backgroundColor = hexbValue;
}

// function to toggle night mode
function handleNightMode() {
  // remove any background color generated by handleRandom()
  document.body.style.backgroundColor = "";

  // switch between dark/light modes
  document.body.classList.toggle("darkMode");

  // change icon depending on mode
  const darkModeBtn = document.getElementById("nightModeBtn");
  darkModeBtn.textContent = darkModeBtn.textContent === "☀️" ? "🌙" : "☀️";
}
